site_name: UPI Specs
repo_url: 'https://github.com/renuanba/mkdocs-upi-api-spec.git'
edit_uri: ''

plugins:
  - search
  - mkdocs-versioning:
      version: 2.1.0

nav:
  - Home: 'index.md'
  - Meta APIs:
      - List Accounts: 'listacc.md'
  - Version: '../'
